spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dev_psql?currentSchema=hamburgueria
    username: postgres
    password: 1998
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none # Ou update, create, etc. dependendo da sua necessidade
server:
  port: 8083